/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LineString } from './lineString';

export class CreateRouteRequest {
    'title'?: string;
    'description'?: string;
    'path'?: LineString;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "LineString"
        }    ];

    static getAttributeTypeMap() {
        return CreateRouteRequest.attributeTypeMap;
    }
}

