/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GroupResponse {
    'name': string;
    'description': string;
    'joinPolicy'?: GroupResponse.JoinPolicyEnum;
    'owner': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "joinPolicy",
            "baseName": "joinPolicy",
            "type": "GroupResponse.JoinPolicyEnum"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GroupResponse.attributeTypeMap;
    }
}

export namespace GroupResponse {
    export enum JoinPolicyEnum {
        INVITEONLY = <any> 'INVITE_ONLY',
        REQUEST = <any> 'REQUEST',
        PUBLIC = <any> 'PUBLIC'
    }
}
