/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuditDto } from './auditDto';
import { LineStringDto } from './lineStringDto';
import { ResourceItem } from './resourceItem';

export class RouteResponse {
    'title': string;
    'description': string;
    'path': LineStringDto;
    'audit': AuditDto;
    'images': Array<ResourceItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "LineStringDto"
        },
        {
            "name": "audit",
            "baseName": "audit",
            "type": "AuditDto"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ResourceItem>"
        }    ];

    static getAttributeTypeMap() {
        return RouteResponse.attributeTypeMap;
    }
}

