/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TokenResponse {
    'accessToken': string;
    'accessTokenExpiration': string;
    'refreshToken': string;
    'refreshTokenExpiration': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string"
        },
        {
            "name": "accessTokenExpiration",
            "baseName": "accessTokenExpiration",
            "type": "string"
        },
        {
            "name": "refreshToken",
            "baseName": "refreshToken",
            "type": "string"
        },
        {
            "name": "refreshTokenExpiration",
            "baseName": "refreshTokenExpiration",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TokenResponse.attributeTypeMap;
    }
}

