openapi: 3.0.0
info:
  title: swagger
  version: '1.0'
  contact:
    name: tyr
tags:
  - name: oauth
  - name: route
  - name: group
servers:
  - url: 'http://localhost:3001'
    description: local-dev
paths:
  /oauth/login:
    post:
      summary: ''
      tags:
        - oauth
      responses:
        '200':
          description: LoginResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        description: LoginRequest
      operationId: login
  /oauth/register:
    post:
      summary: ''
      tags:
        - oauth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
        description: RegistrationRequest
      operationId: register
  /oauth/authorize:
    post:
      summary: ''
      tags:
        - oauth
      responses:
        '301':
          description: Moved Permanently
      description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: response_type
        - schema:
            type: string
          in: query
          name: client_id
        - schema:
            type: string
          in: query
          name: redirect_uri
      operationId: authorize
  /oauth/logout:
    post:
      summary: ''
      tags:
        - oauth
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutRequest'
      operationId: logout
  /route:
    post:
      summary: ''
      tags:
        - route
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      operationId: createRoute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRouteRequest'
        description: ''
  '/route/{id}':
    get:
      summary: Your GET endpoint
      tags:
        - route
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouteResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: getRouteById
    put:
      summary: ''
      tags:
        - route
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRouteRequest'
      operationId: updateRouteById
    delete:
      summary: ''
      tags:
        - route
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: deleteRouteById
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  '/route/{routeId}/share-in-group/{groupId}':
    parameters:
      - name: routeId
        in: path
        required: true
        schema:
          type: string
        description: ''
      - name: groupId
        in: path
        required: true
        schema:
          type: string
    post:
      summary: ''
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: shareInGroup
      tags:
        - route
  /oauth/token:
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
      parameters:
        - schema:
            type: string
          in: query
          name: grant_type
        - schema:
            type: string
          in: query
          name: code
        - schema:
            type: string
          in: query
          name: redirect_uri
        - schema:
            type: string
          in: query
          name: client_id
        - schema:
            type: string
          in: query
          name: refresh_token
      operationId: token
      tags:
        - oauth
  /group:
    post:
      summary: createGroup
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      operationId: createGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
      tags:
        - group
  '/group/{groupId}':
    parameters:
      - schema:
          type: string
        name: groupId
        in: path
        required: true
    get:
      summary: findById
      tags:
        - group
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: ''
      operationId: findById
    put:
      summary: updateGroup
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: updateGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
      tags:
        - group
    delete:
      summary: ''
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - group
  '/group/{groupId}/join':
    parameters:
      - schema:
          type: string
        name: groupId
        in: path
        required: true
    post:
      summary: joinGroup
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: ''
      operationId: joinGroup
      tags:
        - group
  '/group/{groupId}/leave':
    parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
    post:
      summary: leaveGroup
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: leaveGroup
      tags:
        - group
  /group/page:
    get:
      summary: getGroupsPaged
      tags:
        - group
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupPageResponse'
      operationId: getGroupsPaged
  /route/most-popular:
    get:
      summary: mostPopularRoutes
      tags:
        - route
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RouteResponse'
      operationId: getMostPopularRoutes
  /oauth/logout/all:
    post:
      summary: ''
      operationId: post-oauth-logout-all
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
components:
  parameters:
    page:
      name: page
      in: query
      schema:
        type: integer
    size:
      name: size
      in: query
      schema:
        type: integer
  schemas:
    LoginRequest:
      title: LoginRequest
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        clientId:
          type: string
        redirectUri:
          type: string
    LoginResponse:
      title: LoginResponse
      type: object
      properties:
        code:
          type: string
        redirectUri:
          type: string
      required:
        - code
        - redirectUri
    CreateRouteRequest:
      title: CreateRouteRequest
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        path:
          $ref: '#/components/schemas/LineStringDto'
    UpdateRouteRequest:
      title: UpdateRouteRequest
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        path:
          $ref: '#/components/schemas/LineStringDto'
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        cause:
          type: string
        message:
          type: string
      required:
        - cause
    RouteResponse:
      title: RouteResponse
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        path:
          $ref: '#/components/schemas/LineStringDto'
        audit:
          $ref: '#/components/schemas/AuditDto'
        images:
          type: array
          items:
            $ref: '#/components/schemas/ResourceItemResponse'
      required:
        - title
        - description
        - path
        - audit
        - images
    AuditDto:
      title: AuditDto
      type: object
      properties:
        createdBy:
          type: string
        createdAt:
          type: string
        modifiedBy:
          type: string
        modifiedAt:
          type: string
    TokenResponse:
      title: TokenResponse
      type: object
      properties:
        accessToken:
          type: string
        accessTokenExpiration:
          type: string
        refreshToken:
          type: string
        refreshTokenExpiration:
          type: string
      required:
        - accessToken
        - accessTokenExpiration
        - refreshToken
        - refreshTokenExpiration
    RegistrationRequest:
      title: RegistrationRequest
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    RegistrationResponse:
      title: RegistrationResponse
      type: object
      properties:
        userId:
          type: string
      required:
        - userId
    LineStringDto:
      title: LineStringDto
      type: object
      properties:
        type:
          type: string
        coordinates:
          type: array
          items:
            type: array
            items:
              type: number
      required:
        - type
        - coordinates
    GroupRequest:
      title: UpdateGroupRequest
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        joinPolicy:
          $ref: '#/components/schemas/GroupJoinPolicy'
    GroupResponse:
      title: GroupResponse
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        joinPolicy:
          type: string
          enum:
            - INVITE_ONLY
            - REQUEST
            - PUBLIC
        owner:
          type: string
      required:
        - name
        - description
        - access
        - owner
    GroupPageResponse:
      title: GroupPageResponse
      type: object
      allOf:
        - $ref: '#/components/schemas/PageResponse'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/GroupResponse'
    PageResponse:
      title: PageResponse
      type: object
      properties:
        page:
          type: number
        size:
          type: number
        items:
          type: array
          items: {}
      required:
        - page
        - size
        - items
    CreatedRespone:
      title: CreatedRespone
      type: object
      properties:
        id:
          type: string
      required:
        - id
    ResourceItemResponse:
      title: ResourceItemResponse
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        url:
          type: string
      required:
        - id
        - name
        - url
    LogoutRequest:
      title: LogoutRequest
      type: object
      properties:
        accessToken:
          type: string
    GroupJoinPolicy:
      title: GroupJoinPolicy
      type: string
      enum: 
        - INVITE_ONLY
        - REQUEST
        - PUBLIC
