openapi: 3.0.0
info:
  title: swagger
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: local-dev
paths:
  /oauth/login:
    post:
      summary: ''
      responses:
        '200':
          description: LoginResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        description: LoginRequest
  /oauth/register:
    post:
      summary: ''
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
        description: RegistrationRequest
components:
  schemas:
    LoginRequest:
      title: LoginRequest
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        clientId:
          type: string
        redirectUri:
          type: string
    LoginResponse:
      title: LoginResponse
      type: object
      properties:
        code:
          type: string
        redirectUri:
          type: string
