// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AuditDto
 */
export interface AuditDto {
    /**
     * @type {string}
     * @memberof AuditDto
     */
    createdBy?: string;
    /**
     * @type {string}
     * @memberof AuditDto
     */
    createdAt?: string;
    /**
     * @type {string}
     * @memberof AuditDto
     */
    modifiedBy?: string;
    /**
     * @type {string}
     * @memberof AuditDto
     */
    modifiedAt?: string;
}
