// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GroupJoinPolicy,
} from './';

/**
 * @export
 * @interface GroupResponse
 */
export interface GroupResponse {
    /**
     * @type {string}
     * @memberof GroupResponse
     */
    name: string;
    /**
     * @type {string}
     * @memberof GroupResponse
     */
    description: string;
    /**
     * @type {GroupJoinPolicy}
     * @memberof GroupResponse
     */
    joinPolicy?: GroupJoinPolicy;
    /**
     * @type {string}
     * @memberof GroupResponse
     */
    owner: string;
}
