// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GroupJoinPolicy,
} from './';

/**
 * @export
 * @interface GroupRequest
 */
export interface GroupRequest {
    /**
     * @type {string}
     * @memberof GroupRequest
     */
    name?: string;
    /**
     * @type {string}
     * @memberof GroupRequest
     */
    description?: string;
    /**
     * @type {GroupJoinPolicy}
     * @memberof GroupRequest
     */
    joinPolicy?: GroupJoinPolicy;
}
