// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GroupPageResponseAllOf,
    GroupResponse,
    PageResponse,
} from './';

/**
 * @type GroupPageResponse
 * @export
 */
export type GroupPageResponse = GroupPageResponseAllOf & PageResponse;
