// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LineStringDto
 */
export interface LineStringDto {
    /**
     * @type {string}
     * @memberof LineStringDto
     */
    type: string;
    /**
     * @type {Array<Array<number>>}
     * @memberof LineStringDto
     */
    coordinates: Array<Array<number>>;
}
