// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PageResponse
 */
export interface PageResponse {
    /**
     * @type {number}
     * @memberof PageResponse
     */
    page: number;
    /**
     * @type {number}
     * @memberof PageResponse
     */
    size: number;
    /**
     * @type {Array<object>}
     * @memberof PageResponse
     */
    items: Array<object>;
}
