// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AuditDto,
    LineStringDto,
    ResourceItemResponse,
} from './';

/**
 * @export
 * @interface RouteResponse
 */
export interface RouteResponse {
    /**
     * @type {string}
     * @memberof RouteResponse
     */
    title: string;
    /**
     * @type {string}
     * @memberof RouteResponse
     */
    description: string;
    /**
     * @type {LineStringDto}
     * @memberof RouteResponse
     */
    path: LineStringDto;
    /**
     * @type {AuditDto}
     * @memberof RouteResponse
     */
    audit: AuditDto;
    /**
     * @type {Array<ResourceItemResponse>}
     * @memberof RouteResponse
     */
    images: Array<ResourceItemResponse>;
}
