// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * @type {string}
     * @memberof TokenResponse
     */
    accessToken: string;
    /**
     * @type {string}
     * @memberof TokenResponse
     */
    accessTokenExpiration: string;
    /**
     * @type {string}
     * @memberof TokenResponse
     */
    refreshToken: string;
    /**
     * @type {string}
     * @memberof TokenResponse
     */
    refreshTokenExpiration: string;
}
