// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LineStringDto,
} from './';

/**
 * @export
 * @interface UpdateRouteRequest
 */
export interface UpdateRouteRequest {
    /**
     * @type {string}
     * @memberof UpdateRouteRequest
     */
    title?: string;
    /**
     * @type {string}
     * @memberof UpdateRouteRequest
     */
    description?: string;
    /**
     * @type {LineStringDto}
     * @memberof UpdateRouteRequest
     */
    path?: LineStringDto;
}
