// tslint:disable
/**
 * swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders } from '../runtime';
import {
    LogoutRequest,
} from '../models';

export interface PostOauthLogoutAllRequest {
    logoutRequest?: LogoutRequest;
}

/**
 * no description
 */
export class DefaultApi extends BaseAPI {

    /**
     */
    postOauthLogoutAll = ({ logoutRequest }: PostOauthLogoutAllRequest): Observable<void> => {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            path: '/oauth/logout/all',
            method: 'POST',
            headers,
            body: logoutRequest,
        });
    };

}
